seed: 43
device: cuda:1
num_steps_per_env: 24
max_iterations: 60000
empirical_normalization: {}
policy:
  class_name: AsymmetricActorCritic
  init_noise_std: 1.0
  noise_std_type: log
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
  actor_obs_normalization: false
  critic_obs_normalization: false
  latent_dim: 64
  prediction_dim: 6
  history_num_frames: 32
  obs_curr_dim: 46
  policy_history_only: true
  history_encoder_hidden_dims:
  - 512
  - 256
  - 128
  state_estimator_hidden_dims:
  - 128
  - 64
  history_obs_normalization: false
algorithm:
  class_name: PPOAdaptation
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  entropy_coef: 0.01
  desired_kl: 0.01
  max_grad_norm: 1.0
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  normalize_advantage_per_mini_batch: false
  symmetry_cfg: null
  rnd_cfg: null
  adaptation_coef: 1.0
  adaptation_learning_rate: 1.0e-05
  obs_pred_weights:
  - 0.2
  - 0.2
  - 0.2
  - 1.0
  - 1.0
  - 1.0
  obs_pred_target_obs_group: pred
  obs_pred_target_key: null
clip_actions: null
save_interval: 400
experiment_name: uniFP_aliengo_position_force
run_name: A2_base_only_v2
logger: tensorboard
neptune_project: isaaclab
wandb_project: isaaclab
resume: false
load_run: .*
load_checkpoint: model_.*.pt
class_name: OnPolicyRunnerAdaptation
obs_groups:
  policy:
  - policy
  critic:
  - privileged
  pred:
  - pred
