<?xml version="1.0"?>
<package format="3">
  <name>a2_lowlevel</name>
  <version>0.1.0</version>
  <description>Standalone Unitree A2 low-level ROS2 adapter.</description>
  <maintainer email="unitree@unitree.com">Unitree</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>unitree_hg</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
