**

!deploy/
!deploy/a2_piper_stage2/
!deploy/a2_piper_stage2/pyproject.toml
!deploy/a2_piper_stage2/src/
!deploy/a2_piper_stage2/src/**
!deploy/a2_piper_stage2/ros2/
!deploy/a2_piper_stage2/ros2/a2_piper_stage2_direct/
!deploy/a2_piper_stage2/ros2/a2_piper_stage2_direct/**
!deploy/a2_piper_stage2/scripts/
!deploy/a2_piper_stage2/scripts/**
!deploy/a2_piper_stage2/docker/
!deploy/a2_piper_stage2/docker/entrypoint.sh

!ros2/
!ros2/A2/
!ros2/A2/CMakeLists.txt
!ros2/A2/package.xml
!ros2/A2/include/
!ros2/A2/include/**
!ros2/A2/src/
!ros2/A2/src/**
!ros2/A2/scripts/
!ros2/A2/scripts/**
!ros2/A2/config/
!ros2/A2/config/**

!ros2/Piper/
!ros2/Piper/package.xml
!ros2/Piper/setup.py
!ros2/Piper/setup.cfg
!ros2/Piper/resource/
!ros2/Piper/resource/**
!ros2/Piper/piper_bridge/
!ros2/Piper/piper_bridge/**

!policy/
!policy/A2_policy/
!policy/A2_policy/**

!utils/
!utils/cpp_manager_env/
!utils/cpp_manager_env/**
